apiVersion: skaffold/v4beta3
kind: Config

manifests:
  rawYaml:
    - ./infra/*

build:
  local:
    push: false
  artifacts:
    - image: victornkpubre/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
